#!/bin/sh

C_FLAGS="-std=gnu99 -I/usr/include/csmith-2.1.0/"
PROPERTY_FILE="$(mktemp)"
echo "valid-memtrack" > "$PROPERTY_FILE"  #"valid-memtrack" or "label(ERROR)"
PREDATOR_PATH="/home/shooter/FIT/Predator/predator-2013-10-30-d1bd405/sl_build/check-property.sh"

$PREDATOR_PATH --propertyfile "$PROPERTY_FILE" -- "$1" -m64 "$C_FLAGS"
rm -f "$PROPERTY_FILE"