#!/bin/sh

C_FLAGS="-std=gnu99"
PROPERTY_FILE="$(mktemp)"
echo "label(ERROR)" > "$PROPERTY_FILE"
PREDATOR_PATH=/home/shooter/FIT/Predator/predator-2013-10-30-d1bd405/sl_build/check-property.sh

$PREDATOR_PATH --propertyfile "$PROPERTY_FILE" -- $1 -m64 $C_FLAGS
rm -f "$PROPERTY_FILE"
